# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Boiler' do
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Boiler

  

  platform :ios, '9.0'
  target 'BoilerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Boiler-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Boiler-tvOS

  target 'Boiler-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
